from pathlib import Path
p=Path('/home/ubuntu/orbitpress5/app/src/main/assets/index.html')
s=p.read_text()
s=s.replace("const images=draftImages(draft),recipe=draft.recipe||{},recipes=draft.recipes||[],published=", "const images=draftImages(draft),seo=draft.seo||{},pinterest=draft.pinterest||{},recipe=draft.recipe||{},recipes=draft.recipes||[],published=")
needle="""${!published?`<section id=\"preflight\" class=\"notice\"></section>"""
insert="""${!published?`<section class=\"review-metadata-grid\"><article class=\"card metadata-card\"><div class=\"section-head\"><div><p class=\"eyebrow\">Search visibility</p><h2>SEO Review</h2><p class=\"helper\">Review these Yoast-compatible values. They are saved locally and do not change the article unless you edit the article fields.</p></div><span class=\"tag\">editable</span></div><label for=\"reviewFocusKeyphrase\">Focus keyphrase<input id=\"reviewFocusKeyphrase\" type=\"text\" maxlength=\"80\" placeholder=\"e.g. apple pie oatmeal cookies\"></label><label for=\"reviewSeoTitle\">SEO title<input id=\"reviewSeoTitle\" type=\"text\" maxlength=\"160\"></label><label for=\"reviewSeoDescription\">Meta description<textarea id=\"reviewSeoDescription\" rows=\"3\" maxlength=\"160\"></textarea></label><div class=\"metadata-counts\"><span id=\"seoTitleCount\"></span><span id=\"seoDescriptionCount\"></span></div></article><article class=\"card metadata-card\"><div class=\"section-head\"><div><p class=\"eyebrow\">Pinterest publishing</p><h2>Pinterest Review</h2><p class=\"helper\">AI-generated fields stay separate. Review them before using Direct API or manual Pinterest publishing.</p></div><span class=\"tag\">editable</span></div><label for=\"reviewPinterestTitle\">Pinterest title<input id=\"reviewPinterestTitle\" type=\"text\" maxlength=\"100\"></label><label for=\"reviewPinterestDescription\">Pinterest description<textarea id=\"reviewPinterestDescription\" rows=\"4\" maxlength=\"800\"></textarea></label><label for=\"reviewPinterestAlt\">Image alt text<input id=\"reviewPinterestAlt\" type=\"text\" maxlength=\"320\"></label><div class=\"metadata-preview\"><strong>Preview</strong><h3 id=\"pinterestPreviewTitle\"></h3><p id=\"pinterestPreviewDescription\"></p><small id=\"pinterestPreviewAlt\"></small></div></article></section><section id=\"preflight\" class=\"notice\"></section>"`"""
if needle not in s: raise SystemExit('review marker missing')
s=s.replace(needle,insert,1)
old="""draft.title=title;draft.metaDescription=$('editMeta')?.value.trim()||'';draft.slug="""
new="""draft.title=title;draft.metaDescription=$('editMeta')?.value.trim()||'';draft.seo={focusKeyphrase:$('reviewFocusKeyphrase')?.value.trim()||'',title:$('reviewSeoTitle')?.value.trim()||draft.title,metaDescription:$('reviewSeoDescription')?.value.trim()||draft.metaDescription};draft.pinterest={...(draft.pinterest||{}),title:$('reviewPinterestTitle')?.value.trim()||draft.pinterestTitle||draft.title,description:$('reviewPinterestDescription')?.value.trim()||draft.pinterestDescription||draft.metaDescription,altText:$('reviewPinterestAlt')?.value.trim()||draft.pinterestAltText||draft.title};draft.pinterestTitle=draft.pinterest.title;draft.pinterestDescription=draft.pinterest.description;draft.pinterestAltText=draft.pinterest.altText;draft.slug="""
if old not in s: raise SystemExit('save marker missing')
s=s.replace(old,new,1)
old2="""editTitle.value=draft.title||'';editMeta.value=draft.metaDescription||'';editSlug.value=draft.slug||'';editHtml.value=draft.htmlContent||'';editRecipes.value="""
new2="""editTitle.value=draft.title||'';editMeta.value=draft.metaDescription||'';editSlug.value=draft.slug||'';editHtml.value=draft.htmlContent||'';editRecipes.value="""
s=s.replace(old2,new2,1)
# Initialize metadata controls and live preview immediately after the existing edit field setup.
needle3="""renderRecipeImageManager(draft,recipes)}const saveVersion="""
insert3="""renderRecipeImageManager(draft,recipes);$('reviewFocusKeyphrase').value=seo.focusKeyphrase||'';$('reviewSeoTitle').value=seo.title||draft.title||'';$('reviewSeoDescription').value=seo.metaDescription||draft.metaDescription||'';$('reviewPinterestTitle').value=pinterest.title||draft.pinterestTitle||draft.title||'';$('reviewPinterestDescription').value=pinterest.description||draft.pinterestDescription||draft.metaDescription||'';$('reviewPinterestAlt').value=pinterest.altText||draft.pinterestAltText||draft.title||'';const refreshMetadataPreview=()=>{$('seoTitleCount').textContent=`${$('reviewSeoTitle').value.length}/160`;$('seoDescriptionCount').textContent=`${$('reviewSeoDescription').value.length}/160`;$('pinterestPreviewTitle').textContent=$('reviewPinterestTitle').value;$('pinterestPreviewDescription').textContent=$('reviewPinterestDescription').value;$('pinterestPreviewAlt').textContent=`Alt: ${$('reviewPinterestAlt').value}`};['reviewSeoTitle','reviewSeoDescription','reviewPinterestTitle','reviewPinterestDescription','reviewPinterestAlt'].forEach(id=>$(id).addEventListener('input',refreshMetadataPreview));refreshMetadataPreview()}const saveVersion="""
if needle3 not in s: raise SystemExit('render marker missing')
s=s.replace(needle3,insert3,1)
p.write_text(s)
print('Review metadata UI added')
